# This file is part of ABP.
#
# ABP is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# ABP is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with ABP.  If not, see <https://www.gnu.org/licenses/>.
#
# For further information about ABP you can visit
# http://cdsoft.fr/abp

name:                abp
version:             0.1.8.3
github:              "CDSoft/abp"
license:             GPL-3
author:              "Christophe Delord"
maintainer:          "cdsoft.fr"
copyright:           "2019-2020 Christophe Delord"

extra-source-files:
- README.md
- package.yaml
- doc/abp.md
- doc/hello.dot
- stack.yaml

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Abstract Processor for Pandoc
                     Please see the README on GitHub at <https://github.com/CDSoft/abp#readme>

dependencies:
- base >= 4.7 && < 5

_common: &common
  ghc-options:
  - -Wall -Werror
  - -O3
  - -fwarn-unused-do-bind

library:
  <<: *common
  source-dirs: src
  dependencies:
  - bytestring
  - containers
  - cryptohash
  - directory
  - extra
  - filepath
  - pandoc
  - pandoc-csv2table
  - pandoc-types
  - process
  - strict
  - template-haskell
  - temporary
  - text
  - uri-encode

executables:
  abp:
    <<: *common
    main:                abp.hs
    source-dirs:         app
    dependencies:
    - abp
    - pandoc-types
    - text

tests:
  abp-test:
    <<: *common
    main:                Spec.hs
    source-dirs:         test
    dependencies:
    - abp
    - directory
    - exceptions
    - filepath
    - hspec
    - neat-interpolation
    - pandoc
    - temporary
    - text
